spring:            #全局配置
  datasource:
    #    jdbc:mysql://localhost:3306/function：这是 JDBC 连接 URL，指定了数据库的协议（jdbc:mysql）、主机名（localhost）、端口号（3306），以及数据库名称（blog）。
    #    serverTimezone=GMT%2B8：指定数据库服务器的时区为 GMT+8（即中国标准时间）。%2B 是 URL 编码中的加号（+）。
    #    useUnicode=true：确保数据库连接使用 Unicode 字符集。
    #    characterEncoding=utf-8：指定字符编码为 UTF-8，确保数据的读写操作中使用 UTF-8 编码。
    url: jdbc:mysql://localhost:3306/function?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
    #    这是 JDBC 驱动类的名称。对于 MySQL 8 及以上版本，使用 com.mysql.cj.jdbc.Driver。
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: ta030801

mybatis-plus:
  global-config:
    db-config:
      id-type: auto
